### ISSUE TITLE
Postal Code length not rectified

### ISSUE THREAD

**Issue by MorganGellert** [GreenBuildingRegistry/usaddress-scourgify#16]
Postal codes are correctly identified even if they are not the correct length.
Trying `normalize_address_record("1 main st, boston, ma, 2129")` returns with the postal code field "2129" when instead it should have a leading 0.

This truncation can happen a lot when casting a zip code to an integer and then converting it back to a string. It would be nice if scourgify caught this and returned the full string zip code instead.

Additionally, zip code extension lengths are not being enforced either.

In an ideal world the following happens:
"2129" -> "02129"
"02129-44" -> "02129-0044"
"021290044" -> "02129-0044"

**Comment by fablet** [comment]
Resolved in #26
