### ISSUE TITLE
Address with APT but no number throws ValueError

### ISSUE THREAD

**Issue by ian-haven** [GreenBuildingRegistry/usaddress-scourgify#19]
Passing in an address that looks like the following

`dict(address_line_1="6712 THOUSAND ISLANDS RD APT", city="Fort Worth", state="TX", zip="75254")`

causes an uncaught exception at:

```
scourgify/normalize.py", line 549, in normalize_occupancy_type
    index = parsed_list.index(('OccupancyIdentifier', occupancy_id))
ValueError: ('OccupancyIdentifier', None) is not in list
```

**Comment by ses4j** [comment]
This same crash occurs with Unit: 

normalize_address_record('1234 Scott Crescent, Unit, Hilton Head Island, SC 29910')

crashes with the same error.

**Comment by fablet** [comment]
The issue here is because the normalization expects there to be an OccupancyIdentifier anytime there is an OccupancyType.  I can add a try block to the section of code to raise a clearer AddressNormalization error, but an error in this situation is the expected behavior

**Comment by fablet** [comment]
Improved error messaging added in #25
