### ISSUE TITLE
Normalize but need expansion of abbreviations 

### ISSUE THREAD

**Issue by Aj-232425** [GreenBuildingRegistry/usaddress-scourgify#22]
Hi @fablet ,
I hope you are doing great. I came across your scourgify usaddress. Also have gone through the same. But all I need is vice versa .
If you could help me out that'd be appreciated.
For example. Take an address:-  1445 N SOUTHERN AVE STE 2004" I need it to normalize like :- 1445 NORTH SOUTHERN AVENUE SUITE 2004
Where, your lib is converting expanded to abbreviated form of street name , i need expansion of abbreviations.

Hoping for your reply.
Thanks & Regards
Aj

**Comment by fablet** [comment]
You would use a custom yaml config file, per the README:
`You can also customize the address constants used by setting up an address_constants.yaml config file. Allowed keys are:

DIRECTIONAL_REPLACEMENTS
OCCUPANCY_TYPE_ABBREVIATIONS
STATE_ABBREVIATIONS
STREET_TYPE_ABBREVIATIONS
KNOWN_ODDITIES
PROBLEM_ST_TYPE_ABBRVS

To use a custom constants yaml, set the ADDRESS_CONFIG_DIR environment variable with the full path to the directory containing your address_constants.yaml file

export ADDRESS_CONFIG_DIR=/path/to/your/config_dir`


Specifically you would want to create values for:
DIRECTIONAL_REPLACEMENTS
OCCUPANCY_TYPE_ABBREVIATIONS
STATE_ABBREVIATIONS

You can see the constants being used by default in [/scourgify/address_constants.py](https://github.com/GreenBuildingRegistry/usaddress-scourgify/blob/dev/scourgify/address_constants.py)

**Comment by Aj-232425** [comment]
Hello @fablet ,

Thank you so much for reverting . That helped me and also able to achieve the decided approach. I have one more question, i have to use Usaddress-scourgify on millions of addresses, so the thing is that how can I validate the result. Is there any way if I could find out confidence score or probability of output being true. Which can help me out to filter if output is having some  % value of confidence value , should be considered as true positive. 
I hope you'll get the exact requirement i have..
Hoping for your positive response .

Thanks & Regards.
