### ISSUE TITLE
Confidence score to validate output

### ISSUE THREAD

**Issue by Aj-232425** [GreenBuildingRegistry/usaddress-scourgify#23]
Hello @fablet ,

Thank you so much for reverting. Previous issues was closed. So need to open new one.
Your solution helped me and also able to achieve the decided approach. I have one more question, i have to use Usaddress-scourgify on millions of addresses, so the thing is that how can I validate the result. Is there any way if I could find out confidence score or probability of output being true. Which can help me out to filter if output is having some % value of confidence value , should be considered as true positive.
I hope you'll get the exact requirement i have..
Hoping for your positive response .

Thanks & Regards.

**Comment by fablet** [comment]
Per the documentation, the package does not make any attempts at address validation.   Address validation is a fairly involved process that is well out of scope for what this package is attempting achieve.  It's why services like Lob and SmartyStreets exist and charge for it. 
I have not looked into address validation services in a while, so I don't remember if there are any reliable free options out there, but finding a free option that would validate millions of addresses is going to be challenging at best.
To the best of my knowledge, there are no Python packages that either validate or provide a confidence score on their own, without hooking into one of the services.
