### ISSUE TITLE
`normalize_address_record()` adds a space between `#` and unit number

### ISSUE THREAD

**Issue by philiporlando** [GreenBuildingRegistry/usaddress-scourgify#29]
The `normalize_address_record()` function is adding an erroneous space between the `#` symbol and the unit number within the second line address field. 

```python
from scourgify import normalize_address_record

address = "1320 El Capitan Dr #210 DANVILLE CA 94526"

normalize_address_record(address)
# OrderedDict([('address_line_1', '1320 EL CAPITAN DR'), ('address_line_2', '# 210'), ('city', 'DANVILLE'), ('state', 'CA'), ('postal_code', '94526')])
```
I think we should expect to see `#210` returned for the `address_line_2` attribute. 

I am using `usaddress-scourgify 0.5.1`. Happy to provide more details as needed. Thank you!

**Comment by fablet** [comment]
In this case the `#` is being treated as an occupancy type abbreviation.  There is an intended space between all occupancy type abbreviations and the occupancy identifier.  Amongst other things, it makes it easier to separate the identifier from the type, given that type can be expressed in multiple ways for the same address and still be correct.
If you need the `#` to have no separation from the number, you will need to write your own override, either in post handling of the results, or by extending the `NormalizeAddress` class and providing an override for the `normalize_address_components` method.
