### ISSUE TITLE
ImportError: cannot import name 'Normalize' from 'scourgify'

### ISSUE THREAD

**Issue by Lwhieldon** [GreenBuildingRegistry/usaddress-scourgify#32]
When I try to import NormalizeAddress, I get the below error:

ImportError: cannot import name 'Normalize' from 'scourgify'

**Comment by fablet** [comment]
@Lwhieldon There is no `Normalize` in this package, so it would seem you have a typo in your import statement.
The import statement for `NormalizeAddress` is `from scourgify.normalize import NormalizeAddress`.
Note the package is `normalize`, lowercase `n`, and the class is `NormalizeAddress`, one word
